services:
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "8080:8080"
    env_file:
      - .env
    develop:
      watch:
        - path: src/agents/
          action: sync+restart
          target: /app/agents/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/service/
          action: sync+restart
          target: /app/service/
        - path: src/core/
          action: sync+restart
          target: /app/core/
        - path: src/memory/
          action: sync+restart
          target: /app/memory/

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    environment:
      - AGENT_URL=http://agent_service:8080
    develop:
      watch:
        - path: src/client/
          action: sync+restart
          target: /app/client/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/streamlit_app.py
          action: sync+restart
          target: /app/streamlit_app.py

  rule_engine_api:
    build:
      context: .
      dockerfile: docker/Dockerfile.rule_engine
    ports:
      - "8090:8080"
    volumes:
      - ./rule_enginge_api/src:/app/src
      - ./rule_enginge_api/configurations:/app/configurations
      - ./rule_enginge_api/rules:/app/rules
    develop:
      watch:
        - path: rule_enginge_api/src/
          action: sync+restart
          target: /app/src/
        - path: rule_enginge_api/configurations/
          action: sync
          target: /app/configurations/
        - path: rule_enginge_api/rules/
          action: sync
          target: /app/rules/
