spring:
  application:
    name: traffic-light-validator
  main:
    banner-mode: "console"

server:
  port: 9090
  servlet:
    context-path: /
  compression:
    enabled: true

# OpenAPI Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  packages-to-scan: de.trafficvalidator.controller
  show-actuator: true

storage:
  type: file  # Options: 'file' or 'database'
  basePath: configurations
  rulesPath: de/trafficvalidator/rules

logging:
  level:
    root: INFO
    de.trafficvalidator: DEBUG
    de.trafficvalidator.parser: INFO
    de.trafficvalidator.util: INFO
    org.springframework: INFO
    # Enhanced Drools rule execution logging
    org.drools: INFO
    org.drools.core: DEBUG    # Core engine operations
    org.kie.kogito: DEBUG     # Kogito/Drools 8 specific logging
    org.kie.kogito.rules: TRACE 

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always